version: 2
project_name: terraform-provider-active24

before:
  hooks:
    - go mod tidy

builds:
  - id: provider
    main: ./
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    # Terraform Registry requires the binary INSIDE each zip to be named with _v<version>
    binary: "terraform-provider-active24_v{{ .Version }}"

archives:
  - id: archive
    # Terraform Registry expects zip
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'SHA256SUMS'
  algorithm: sha256
  extra_files: []

signs:
  - cmd: gpg
    args: ["--batch", "--local-user", "{{ .Env.GPG_FINGERPRINT }}", "--armor", "--output", "${signature}", "--detach-sign", "${artifact}"]
    signature: "${artifact}.sig"
    artifacts: checksum

release:
  prerelease: false


